# Generated by Django 6.0.5 (compatible with 5.2) on 2026-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="has_thumbnail",
            field=models.BooleanField(default=False),
        ),
    ]
